### ISSUE TITLE
支持Sea.js 2.1.1

### ISSUE THREAD

**Issue by elppac** [seajs/seajs-text#10]
现在这份代码不支持Sea.js 2.1.1，需要把define(function() { .... }); 改成 (function(seajs){..})(seajs);

来至 ali elppa.chengp

**Comment by afc163** [comment]
对，master 里的代码是兼容尚未发布的 seajs@2.2.0 的。

需要兼容 seajs@2.1.x 的，请使用 tag 1.0.0/1.0.1 的代码。
