### ISSUE TITLE
能写个seajs-text example 吗？

### ISSUE THREAD

**Issue by peichao01** [seajs/seajs-text#11]
**唠叨**：以前的项目是用的requirejs的，当时试过seajs，虽然想支持seajs，但是文档等真是不给力，尽管requirejs全是英文的，但是稍微一用都很顺畅，非常给力，而且社区很好，还有非常多的项目支持requirejs，比如 symfony 有专门配置requirejs的bundle。总之，非常简单就用起来的，开发+部署，非常非常简单易用。
反观seajs，总是有很多不顺心的地方。特别是ID和路径的问题。

seajs既然有路径即为ID，且必须一致，为什么 seajs-text 这种插件要用define这种模块机制，而且，还已经写好了可能在项目中根本就不一样的ID路径？

现在的问题是，试了很多方式，seajs-text 的 factory函数就不会被执行

``` html
<script src="path/to/sea.js"></script>
<script src="path/to/seajs-text.js"></script>

<script>
define("main", function(require) {
  //此模块的 factory 函数能够被执行
  // You can require `.tpl` file directly
  var tpl = require("./data.tpl")

});
seajs.use('main');
</script>
```

目录结构为：

```
---www
  |__index.html
  |__data.tpl
  |__sea.js
  |__seajs-text.js
```

seajs-text.js 默认的ID为：`seajs/seajs-text/1.0.3/seajs-text-debug`，当前的情况下，改为：`seajs-text` 然后文件最下面的 `seajs.require('seajs-text')`

无论怎样 seajs-text 的工厂函数 就是不会被执行

PS：像这种 seajs-text 紧接着 seajs加载的文件，**何必用define模块呢**？还这么多麻烦。

直接改成`(function(){..seajs-text..`})(); 用起来也挺好。
而且如果选择用 seajs-text 的话，一般来说都会把这两个文件打包在一起的吧。

**想知道这么设计的原因**~~

**Comment by afc163** [comment]
seajs-text 的最新版下面有 `seajs.require('seajs-text')` 的代码，这个需要等到 seajs@2.2.0 发布后才可以运行，请先使用较低的版本。

https://github.com/seajs/seajs-text#seajs-text

**Comment by afc163** [comment]
seajs 的插件封装成 CMD 模块是为了和整个生态圈保持一致，其实非常蛋疼。。。

**Comment by afc163** [comment]
这块现在没资源，hold 住了，非常难过。

等 @lizzie 休假回来，尽快搞定吧。

**Comment by afc163** [comment]
https://github.com/seajs/seajs/issues/944

**Comment by yyclaw** [comment]
@afc163 经常有人升级了插件而没升级 SeaJS，导致使用时出现 bug。既然如此，何不建个 stable 分支，并默认显示，一目了然，也不用切换 tag 分支

cc @lifesinger

**Comment by popomore** [comment]
已经改回来了，seajs 低版本也可以使用。
