### ISSUE TITLE
seajs加载文本文件返回null

### ISSUE THREAD

**Issue by flicat** [seajs/seajs-text#12]
为了兼容seajs 2.1.1，已经将seajs-text改成了(function(seajs) {})(seajs)，请求已经发出，响应有返回文本，但是回调函数没有执行，请问大大们这个是什么原因呢？

**Comment by afc163** [comment]
给重现页面吧。。

**Comment by flicat** [comment]
说明一下，我已经把seajs和text插件放到了同一个文件中。会不会有什么问题？

**Comment by flicat** [comment]
@afc163 额，没有线上页面，都是我本地在跑……

**Comment by flicat** [comment]
哦！！！问题解决，globalEval的前后文问题！！！？？？

**Comment by flicat** [comment]
……………………不知道是什么原因……换个环境又不行了。。。坐等seajs2.2.0

**Comment by afc163** [comment]
搞一个线上页面。

**Comment by flicat** [comment]
……没权限……有问题的页面不让传……

**Comment by afc163** [comment]
你自己模拟一个静态 demo 不行吗？
