### ISSUE TITLE
seajs插件如何打包合并啊？

### ISSUE THREAD

**Issue by mopduan** [seajs/seajs-text#13]
在代码中使用了 require('./seajs-text');插件，但是没效果，preload的方式会导致多一个请求，有什么好办法？

**Comment by army8735** [comment]
同步script标签或者合并到seajs上

**Comment by mopduan** [comment]
怎么合并到seajs上？

**Comment by mopduan** [comment]
有在线选择插件进行合并打包的工具么？

**Comment by army8735** [comment]
么有……反正就一个文件，实在懒粘贴复制都行

**Comment by mopduan** [comment]
我复制到最后一行不生效，复制的位置有要求吧？

**Comment by mopduan** [comment]
现在生效了，不过是采用ajax的方法load的，有跨域问题
