### ISSUE TITLE
插件内容依赖了importstyle却未加打包构建

### ISSUE THREAD

**Issue by eyson** [seajs/seajs-text#15]
EX.
  exec: function(uri, content) {
    var code = [
      'define("' + uri + '#", ["importstyle"], function(require, exports, module) {',

还有就是为嘛编码都不写 “;” 号结束呢？

**Comment by afc163** [comment]
1. 这个逻辑和 handlebars 应该是一样的。https://github.com/seajs/seajs-text/pull/14
2. 为啥一定要加 `;` ？

**Comment by eyson** [comment]
@afc163 
1、`应该`？额，这种情况是不是要在文档里说明下比较好呀。
2、为啥不写`;`？

**Comment by afc163** [comment]
1. 这个新特性我不是很了解。你可以跟进到 #14 里去看看
2. 为啥要写`;`？

**Comment by afc163** [comment]
https://github.com/lifesinger/lifesinger.github.com/issues/98
