### ISSUE TITLE
seajs-text 内置的 handlebars引擎require为null

### ISSUE THREAD

**Issue by flyyang** [seajs/seajs-text#21]
参照中文文档，配置config.

seajs.config({
  alias: {
    handlebars: 'path/to/handlebars'
  }
})
然后在模块代码中，就可以直接获取编译后的 handlebars 模块函数了：

  var compiled = require('./test.handlebars')

seajs-text，在去require handlbars时，为null。

**Comment by flyyang** [comment]
找到问题。handlebars文件非CMD模块。

问题是hanllebars是通过spm下载的，好坑。。

**Comment by afc163** [comment]
spmjs.io 上存放的不是 CMD 模块，是 CommonJS 模块。建议使用 spm 官方文档推荐的方式进行加载。

spm3 以后，和 Sea.js 不再有直接关联。
