### ISSUE TITLE
seajs-text插件引用问题

### ISSUE THREAD

**Issue by Lancezh** [seajs/seajs-text#9]
根据 https://github.com/seajs/seajs-text/issues/1  文档所述

在页面引入 seajs 后 引入 seajs-text 插件 

```
<script src="path/to/sea.js"></script>
<script src="path/to/seajs-text.js"></script>
```

应该就可以直接使用  require('./xxx.tpl')之类的引入模板文件

但使用时发现会出错，还是去找的 xxx.tpl.js

查看后发现 seajs-text 代码中最后一行 用的是 seajs.require('......')

我改为seajs.use('.....')   后就正常了

seajs 版本 2.1.1
seajs-text版本 1.0.3

**Comment by afc163** [comment]
@lifesinger 看看很快就有了插件版本依赖的问题。

**Comment by afc163** [comment]
seajs.require 的要等 seajs@2.2.0 出来才能用，现在有问题。

先用 [1.0.2](https://github.com/seajs/seajs-text/tree/1.0.2) 版本吧。 不过这个版本可能和 preload 会有点冲突。

或者先干脆用最简单的包装的 1.0.2 版本，这样问题最少。https://github.com/seajs/seajs-text/tree/08e4137560555ef2163bbcb73b14a9a62b561177

**Comment by Lancezh** [comment]
这样子。 扫了一眼 1.0.2。      和 1.0.3 的差异 好像就最后的 require && use

**Comment by afc163** [comment]
上面那个链接是改成 seajs.use 前的包装版本。

**Comment by vichajser** [comment]
多谢@afc163  sea.require 改为 use 啊 use啊 改为 use 啊 use啊

**Comment by afc163** [comment]
改为 use 的话，preload 会有问题。等待最近的插件更新吧。

**Comment by popomore** [comment]
已经把 use 和 require 去掉了
